use std::net::SocketAddr;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
pub struct Config {
    pub listen_addr: SocketAddr,
    pub binary_path: PathBuf,
    pub update_command: PathBuf,
    pub hmac_secret_path: PathBuf,
    #[serde(default = "default_repo")]
    pub github_repo: String,
    #[serde(default)]
    pub dry_run: bool,
    #[serde(default = "default_rate_limit")]
    pub rate_limit_seconds: u64,
    #[serde(default = "default_skew")]
    pub clock_skew_tolerance_seconds: i64,
}

fn default_repo() -> String {
    "freenet/freenet-core".to_string()
}
fn default_rate_limit() -> u64 {
    600
}
fn default_skew() -> i64 {
    300
}

impl Config {
    pub fn from_path(path: &Path) -> Result<Self> {
        let raw = std::fs::read_to_string(path)
            .with_context(|| format!("read config {}", path.display()))?;
        toml::from_str(&raw).context("parse config TOML")
    }

    pub fn load_secret(&self) -> Result<Vec<u8>> {
        let bytes = std::fs::read(&self.hmac_secret_path)
            .with_context(|| format!("read HMAC secret {}", self.hmac_secret_path.display()))?;
        // The secret may be hex-encoded with a trailing newline (typical when
        // generated by `openssl rand -hex 32 > hmac.key`); accept either raw
        // bytes or hex by trimming whitespace and trying hex first.
        let trimmed: Vec<u8> = bytes
            .iter()
            .copied()
            .filter(|b| !b.is_ascii_whitespace())
            .collect();
        let decoded = match hex::decode(&trimmed) {
            Ok(d) if d.len() >= 32 => d,
            _ if bytes.len() >= 32 => bytes,
            Ok(d) => anyhow::bail!(
                "HMAC secret hex-decoded to {} bytes, need at least 32",
                d.len()
            ),
            _ => anyhow::bail!(
                "HMAC secret is {} bytes; need at least 32 raw bytes or 64 hex chars",
                bytes.len()
            ),
        };
        Ok(decoded)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_minimal_config() {
        let toml_src = r#"
listen_addr = "127.0.0.1:9876"
binary_path = "/usr/local/bin/freenet"
update_command = "/usr/local/bin/gateway-auto-update.sh"
hmac_secret_path = "/etc/freenet-release-agent/hmac.key"
"#;
        let cfg: Config = toml::from_str(toml_src).unwrap();
        assert_eq!(cfg.github_repo, "freenet/freenet-core");
        assert_eq!(cfg.rate_limit_seconds, 600);
        assert_eq!(cfg.clock_skew_tolerance_seconds, 300);
        assert!(!cfg.dry_run);
    }

    #[test]
    fn parses_full_config() {
        let toml_src = r#"
listen_addr = "127.0.0.1:9876"
binary_path = "/usr/local/bin/freenet"
update_command = "/usr/local/bin/gateway-auto-update.sh"
hmac_secret_path = "/etc/freenet-release-agent/hmac.key"
github_repo = "freenet/freenet-core"
dry_run = true
rate_limit_seconds = 60
clock_skew_tolerance_seconds = 120
"#;
        let cfg: Config = toml::from_str(toml_src).unwrap();
        assert!(cfg.dry_run);
        assert_eq!(cfg.rate_limit_seconds, 60);
        assert_eq!(cfg.clock_skew_tolerance_seconds, 120);
    }
}
