// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ContractContainer, ContractContainerT } from '../common/contract-container.js';
import { ContractKey, ContractKeyT } from '../common/contract-key.js';


export class GetResponse implements flatbuffers.IUnpackableObject<GetResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetResponse(bb:flatbuffers.ByteBuffer, obj?:GetResponse):GetResponse {
  return (obj || new GetResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetResponse(bb:flatbuffers.ByteBuffer, obj?:GetResponse):GetResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key(obj?:ContractKey):ContractKey|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ContractKey()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

contract(obj?:ContractContainer):ContractContainer|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ContractContainer()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

state(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

stateLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

stateArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startGetResponse(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static addContract(builder:flatbuffers.Builder, contractOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, contractOffset, 0);
}

static addState(builder:flatbuffers.Builder, stateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, stateOffset, 0);
}

static createStateVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startStateVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endGetResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // key
  builder.requiredField(offset, 6) // contract
  builder.requiredField(offset, 8) // state
  return offset;
}


unpack(): GetResponseT {
  return new GetResponseT(
    (this.key() !== null ? this.key()!.unpack() : null),
    (this.contract() !== null ? this.contract()!.unpack() : null),
    this.bb!.createScalarList<number>(this.state.bind(this), this.stateLength())
  );
}


unpackTo(_o: GetResponseT): void {
  _o.key = (this.key() !== null ? this.key()!.unpack() : null);
  _o.contract = (this.contract() !== null ? this.contract()!.unpack() : null);
  _o.state = this.bb!.createScalarList<number>(this.state.bind(this), this.stateLength());
}
}

export class GetResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public key: ContractKeyT|null = null,
  public contract: ContractContainerT|null = null,
  public state: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const key = (this.key !== null ? this.key!.pack(builder) : 0);
  const contract = (this.contract !== null ? this.contract!.pack(builder) : 0);
  const state = GetResponse.createStateVector(builder, this.state);

  GetResponse.startGetResponse(builder);
  GetResponse.addKey(builder, key);
  GetResponse.addContract(builder, contract);
  GetResponse.addState(builder, state);

  return GetResponse.endGetResponse(builder);
}
}
