version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
    # Put all updates in one PR
    groups:
      nix:
        patterns:
          - "*"
