// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ContractCode, ContractCodeT } from '../common/contract-code.js';
import { ContractKey, ContractKeyT } from '../common/contract-key.js';


export class WasmContractV1 implements flatbuffers.IUnpackableObject<WasmContractV1T> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WasmContractV1 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWasmContractV1(bb:flatbuffers.ByteBuffer, obj?:WasmContractV1):WasmContractV1 {
  return (obj || new WasmContractV1()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWasmContractV1(bb:flatbuffers.ByteBuffer, obj?:WasmContractV1):WasmContractV1 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WasmContractV1()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

data(obj?:ContractCode):ContractCode|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ContractCode()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

parameters(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

parametersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

parametersArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

key(obj?:ContractKey):ContractKey|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new ContractKey()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startWasmContractV1(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, dataOffset, 0);
}

static addParameters(builder:flatbuffers.Builder, parametersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, parametersOffset, 0);
}

static createParametersVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startParametersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, keyOffset, 0);
}

static endWasmContractV1(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // data
  builder.requiredField(offset, 6) // parameters
  builder.requiredField(offset, 8) // key
  return offset;
}


unpack(): WasmContractV1T {
  return new WasmContractV1T(
    (this.data() !== null ? this.data()!.unpack() : null),
    this.bb!.createScalarList<number>(this.parameters.bind(this), this.parametersLength()),
    (this.key() !== null ? this.key()!.unpack() : null)
  );
}


unpackTo(_o: WasmContractV1T): void {
  _o.data = (this.data() !== null ? this.data()!.unpack() : null);
  _o.parameters = this.bb!.createScalarList<number>(this.parameters.bind(this), this.parametersLength());
  _o.key = (this.key() !== null ? this.key()!.unpack() : null);
}
}

export class WasmContractV1T implements flatbuffers.IGeneratedObject {
constructor(
  public data: ContractCodeT|null = null,
  public parameters: (number)[] = [],
  public key: ContractKeyT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const data = (this.data !== null ? this.data!.pack(builder) : 0);
  const parameters = WasmContractV1.createParametersVector(builder, this.parameters);
  const key = (this.key !== null ? this.key!.pack(builder) : 0);

  WasmContractV1.startWasmContractV1(builder);
  WasmContractV1.addData(builder, data);
  WasmContractV1.addParameters(builder, parameters);
  WasmContractV1.addKey(builder, key);

  return WasmContractV1.endWasmContractV1(builder);
}
}
