//! Regression tests for which CAs HTTPS clients trust.
//!
//! Networks that intercept TLS (corporate proxies) re-sign every certificate
//! with a CA the administrator installed in the OS trust store. With only the
//! bundled webpki roots, `freenet service report` failed there with
//! `invalid peer certificate: UnknownIssuer`. It now adds the OS store through
//! `freenet::util::os_trust`; every other client deliberately does not (see
//! that module), and the negative control below pins that too.
//!
//! A local HTTPS server stands in for the proxy: its certificate chains to a
//! throwaway CA (`tests/data/tls_native_roots/`, valid 2020 to 2126,
//! regenerated by `generate.sh` there) that is "installed" via
//! `SSL_CERT_FILE`. rustls-native-certs reads that in place of the platform
//! store on every OS (checked in its source; CI runs this test on Linux only).
//! This must stay the only test in this binary, because it sets that
//! process-global env var.

use std::sync::Arc;
use std::time::Duration;

use freenet::util::os_trust::add_os_root_certificates;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;
use tokio_rustls::TlsAcceptor;
use tokio_rustls::rustls::{self, pki_types};

const CA_PEM_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/data/tls_native_roots/ca.pem"
);
const LEAF_CERT_DER: &[u8] = include_bytes!("data/tls_native_roots/leaf.der");
const LEAF_KEY_DER: &[u8] = include_bytes!("data/tls_native_roots/leaf.key.der");

/// Serves a fixed `200 ok` over HTTPS on an ephemeral loopback port.
async fn spawn_https_server() -> u16 {
    let config = rustls::ServerConfig::builder_with_provider(Arc::new(
        rustls::crypto::ring::default_provider(),
    ))
    .with_safe_default_protocol_versions()
    .unwrap()
    .with_no_client_auth()
    .with_single_cert(
        vec![pki_types::CertificateDer::from(LEAF_CERT_DER.to_vec())],
        pki_types::PrivateKeyDer::Pkcs8(pki_types::PrivatePkcs8KeyDer::from(LEAF_KEY_DER.to_vec())),
    )
    .unwrap();
    let acceptor = TlsAcceptor::from(Arc::new(config));
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    tokio::spawn(async move {
        while let Ok((tcp, _)) = listener.accept().await {
            let acceptor = acceptor.clone();
            tokio::spawn(async move {
                let serve = async {
                    let mut tls = acceptor.accept(tcp).await?;
                    let mut buf = [0u8; 4096];
                    let _request_len = tls.read(&mut buf).await?;
                    tls.write_all(
                        b"HTTP/1.1 200 OK\r\ncontent-length: 2\r\nconnection: close\r\n\r\nok",
                    )
                    .await?;
                    tls.shutdown().await
                };
                // An error is the expected outcome for the negative control's
                // rejected handshake; the client side asserts on it.
                serve.await.ok();
            });
        }
    });
    port
}

#[test]
fn only_opted_in_clients_trust_ca_installed_in_os_trust_store() {
    // SAFETY: set before the runtime exists, so no other thread can be reading
    // the environment. This is the only test in this binary.
    unsafe {
        std::env::set_var("SSL_CERT_FILE", CA_PEM_PATH);
        // cargo exports SSL_CERT_FILE and SSL_CERT_DIR (its probed system CA
        // paths) to the tests it runs; a leftover SSL_CERT_DIR would be loaded
        // alongside the file.
        std::env::remove_var("SSL_CERT_DIR");
    }
    tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap()
        .block_on(check_trust());
}

async fn check_trust() {
    let port = spawn_https_server().await;
    let url = format!("https://127.0.0.1:{port}/");

    // Negative control, and a pin on the workspace default: a client that does
    // not opt in must reject the OS-store CA. This fails if native roots are
    // ever enabled workspace-wide, which would let any OS-installed CA serve
    // update downloads while release signatures are optional.
    let default_client = test_client_builder().build().unwrap();
    let err = default_client
        .get(&url)
        .send()
        .await
        .expect_err("a client that does not opt in must not trust the OS trust store");
    assert!(
        format!("{err:?}").contains("UnknownIssuer"),
        "expected an UnknownIssuer rejection, got: {err:?}"
    );

    // The helper `freenet service report` builds its client with.
    let (builder, os_trust) = add_os_root_certificates(test_client_builder());
    assert_eq!(
        (os_trust.found, os_trust.added),
        (1, 1),
        "SSL_CERT_FILE holds exactly the test CA: {os_trust}"
    );
    // The override is named, since it is the user's clue when it is stale.
    assert_eq!(
        os_trust.to_string(),
        format!(
            "1 of 1 certificates from SSL_CERT_FILE={CA_PEM_PATH} added, in place of the OS trust store"
        )
    );
    let client = builder.build().unwrap();
    let response = client
        .get(&url)
        .send()
        .await
        .expect("a CA in the OS trust store must be trusted (TLS-intercepting networks)");
    assert_eq!(response.text().await.unwrap(), "ok");
}

/// Bypasses any proxy in the environment (the population this test is about
/// often has one) and bounds a hung handshake. Neither touches root trust.
fn test_client_builder() -> reqwest::ClientBuilder {
    reqwest::Client::builder()
        .no_proxy()
        .timeout(Duration::from_secs(10))
}
