// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { WasmDelegateV1, WasmDelegateV1T } from '../client-request/wasm-delegate-v1.js';


export enum DelegateType {
  NONE = 0,
  WasmDelegateV1 = 1
}

export function unionToDelegateType(
  type: DelegateType,
  accessor: (obj:WasmDelegateV1) => WasmDelegateV1|null
): WasmDelegateV1|null {
  switch(DelegateType[type]) {
    case 'NONE': return null; 
    case 'WasmDelegateV1': return accessor(new WasmDelegateV1())! as WasmDelegateV1;
    default: return null;
  }
}

export function unionListToDelegateType(
  type: DelegateType, 
  accessor: (index: number, obj:WasmDelegateV1) => WasmDelegateV1|null, 
  index: number
): WasmDelegateV1|null {
  switch(DelegateType[type]) {
    case 'NONE': return null; 
    case 'WasmDelegateV1': return accessor(index, new WasmDelegateV1())! as WasmDelegateV1;
    default: return null;
  }
}
