// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class DelegateKey implements flatbuffers.IUnpackableObject<DelegateKeyT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DelegateKey {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDelegateKey(bb:flatbuffers.ByteBuffer, obj?:DelegateKey):DelegateKey {
  return (obj || new DelegateKey()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDelegateKey(bb:flatbuffers.ByteBuffer, obj?:DelegateKey):DelegateKey {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DelegateKey()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

keyLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

keyArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

codeHash(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

codeHashLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

codeHashArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startDelegateKey(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static createKeyVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startKeyVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addCodeHash(builder:flatbuffers.Builder, codeHashOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, codeHashOffset, 0);
}

static createCodeHashVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startCodeHashVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endDelegateKey(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // key
  builder.requiredField(offset, 6) // code_hash
  return offset;
}

static createDelegateKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset, codeHashOffset:flatbuffers.Offset):flatbuffers.Offset {
  DelegateKey.startDelegateKey(builder);
  DelegateKey.addKey(builder, keyOffset);
  DelegateKey.addCodeHash(builder, codeHashOffset);
  return DelegateKey.endDelegateKey(builder);
}

unpack(): DelegateKeyT {
  return new DelegateKeyT(
    this.bb!.createScalarList<number>(this.key.bind(this), this.keyLength()),
    this.bb!.createScalarList<number>(this.codeHash.bind(this), this.codeHashLength())
  );
}


unpackTo(_o: DelegateKeyT): void {
  _o.key = this.bb!.createScalarList<number>(this.key.bind(this), this.keyLength());
  _o.codeHash = this.bb!.createScalarList<number>(this.codeHash.bind(this), this.codeHashLength());
}
}

export class DelegateKeyT implements flatbuffers.IGeneratedObject {
constructor(
  public key: (number)[] = [],
  public codeHash: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const key = DelegateKey.createKeyVector(builder, this.key);
  const codeHash = DelegateKey.createCodeHashVector(builder, this.codeHash);

  return DelegateKey.createDelegateKey(builder,
    key,
    codeHash
  );
}
}
