// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DelegateContainer, DelegateContainerT } from '../client-request/delegate-container.js';


export class RegisterDelegate implements flatbuffers.IUnpackableObject<RegisterDelegateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RegisterDelegate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRegisterDelegate(bb:flatbuffers.ByteBuffer, obj?:RegisterDelegate):RegisterDelegate {
  return (obj || new RegisterDelegate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRegisterDelegate(bb:flatbuffers.ByteBuffer, obj?:RegisterDelegate):RegisterDelegate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RegisterDelegate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

delegate(obj?:DelegateContainer):DelegateContainer|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DelegateContainer()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

cipher(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

cipherLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

cipherArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

nonce(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

nonceLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

nonceArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startRegisterDelegate(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addDelegate(builder:flatbuffers.Builder, delegateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, delegateOffset, 0);
}

static addCipher(builder:flatbuffers.Builder, cipherOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, cipherOffset, 0);
}

static createCipherVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startCipherVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addNonce(builder:flatbuffers.Builder, nonceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nonceOffset, 0);
}

static createNonceVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startNonceVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endRegisterDelegate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // delegate
  builder.requiredField(offset, 6) // cipher
  builder.requiredField(offset, 8) // nonce
  return offset;
}

static createRegisterDelegate(builder:flatbuffers.Builder, delegateOffset:flatbuffers.Offset, cipherOffset:flatbuffers.Offset, nonceOffset:flatbuffers.Offset):flatbuffers.Offset {
  RegisterDelegate.startRegisterDelegate(builder);
  RegisterDelegate.addDelegate(builder, delegateOffset);
  RegisterDelegate.addCipher(builder, cipherOffset);
  RegisterDelegate.addNonce(builder, nonceOffset);
  return RegisterDelegate.endRegisterDelegate(builder);
}

unpack(): RegisterDelegateT {
  return new RegisterDelegateT(
    (this.delegate() !== null ? this.delegate()!.unpack() : null),
    this.bb!.createScalarList<number>(this.cipher.bind(this), this.cipherLength()),
    this.bb!.createScalarList<number>(this.nonce.bind(this), this.nonceLength())
  );
}


unpackTo(_o: RegisterDelegateT): void {
  _o.delegate = (this.delegate() !== null ? this.delegate()!.unpack() : null);
  _o.cipher = this.bb!.createScalarList<number>(this.cipher.bind(this), this.cipherLength());
  _o.nonce = this.bb!.createScalarList<number>(this.nonce.bind(this), this.nonceLength());
}
}

export class RegisterDelegateT implements flatbuffers.IGeneratedObject {
constructor(
  public delegate: DelegateContainerT|null = null,
  public cipher: (number)[] = [],
  public nonce: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const delegate = (this.delegate !== null ? this.delegate!.pack(builder) : 0);
  const cipher = RegisterDelegate.createCipherVector(builder, this.cipher);
  const nonce = RegisterDelegate.createNonceVector(builder, this.nonce);

  return RegisterDelegate.createRegisterDelegate(builder,
    delegate,
    cipher,
    nonce
  );
}
}
