// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { DelegateKey, DelegateKeyT } from '../client-request/delegate-key.js';


export class UnregisterDelegate implements flatbuffers.IUnpackableObject<UnregisterDelegateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UnregisterDelegate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUnregisterDelegate(bb:flatbuffers.ByteBuffer, obj?:UnregisterDelegate):UnregisterDelegate {
  return (obj || new UnregisterDelegate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUnregisterDelegate(bb:flatbuffers.ByteBuffer, obj?:UnregisterDelegate):UnregisterDelegate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UnregisterDelegate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key(obj?:DelegateKey):DelegateKey|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DelegateKey()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startUnregisterDelegate(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static endUnregisterDelegate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // key
  return offset;
}

static createUnregisterDelegate(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset):flatbuffers.Offset {
  UnregisterDelegate.startUnregisterDelegate(builder);
  UnregisterDelegate.addKey(builder, keyOffset);
  return UnregisterDelegate.endUnregisterDelegate(builder);
}

unpack(): UnregisterDelegateT {
  return new UnregisterDelegateT(
    (this.key() !== null ? this.key()!.unpack() : null)
  );
}


unpackTo(_o: UnregisterDelegateT): void {
  _o.key = (this.key() !== null ? this.key()!.unpack() : null);
}
}

export class UnregisterDelegateT implements flatbuffers.IGeneratedObject {
constructor(
  public key: DelegateKeyT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const key = (this.key !== null ? this.key!.pack(builder) : 0);

  return UnregisterDelegate.createUnregisterDelegate(builder,
    key
  );
}
}
