[package]
name = "freenet-email-ui"
version = "0.0.1"
edition = "2021"
rust-version = "1.71.1"
resolver = "2"
publish = false
default-run = "app"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "app"

[dependencies]
bs58 = "0.5"
arc-swap = "1.6"
rand_chacha = "0.3"
chrono = { workspace = true, features = ["wasmbind"] }
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "0fec47d" }
futures = "0.3"
rsa = { workspace = true }
chacha20poly1305 = "0.10"
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { version = "0.1" }
tracing-subscriber = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
once_cell = "1"
rand = { version = "0.8", features = ["std"] }

freenet-email-inbox = { path = "../contracts/inbox", features = ["wasmbind"] }
locutus-dev = { path = "../../../crates/locutus-dev", optional = true }
locutus-stdlib = { workspace = true, features = ["net"] }
locutus-aft-interface = { workspace = true }
identity-management = { path = "../../../modules/identity-management" }

[target.'cfg(target_family = "wasm")'.dependencies]
dioxus-web = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "0fec47d" }
getrandom = { version = "*", features = ["js"] }
locutus-stdlib = { workspace = true, features = ["net"] }
serde-wasm-bindgen = { version = "0.5" }

[target.'cfg(target_family = "wasm")'.dependencies.web-sys]
version = "0.3"
features = [
  "BinaryType",
  "Blob",
  "console",
  "ErrorEvent",
#   "FileReader",
#   "MessageEvent",
#   "ProgressEvent",
  "WebSocket",
  "Window"
]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "0fec47d" }

[features]
default = ["ui-testing"]
ui-testing = []
use-node = []
build-binary = ["locutus-dev"]
