[package]
name = "inbox-identity-management"
version = "0.1.0"
edition = "2021"

[dependencies]
locutus-stdlib = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
locutus-stdlib = { workspace = true, features = ["testing"] }
locutus-runtime = { path = "../../../../crates/locutus-runtime", version = "0.0.3" }
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "fmt"] }

[features]
node = []

[lib]
crate-type = ["cdylib"]
