// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class StateUpdate implements flatbuffers.IUnpackableObject<StateUpdateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StateUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStateUpdate(bb:flatbuffers.ByteBuffer, obj?:StateUpdate):StateUpdate {
  return (obj || new StateUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStateUpdate(bb:flatbuffers.ByteBuffer, obj?:StateUpdate):StateUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StateUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

state(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

stateLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

stateArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startStateUpdate(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addState(builder:flatbuffers.Builder, stateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, stateOffset, 0);
}

static createStateVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startStateVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endStateUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // state
  return offset;
}

static createStateUpdate(builder:flatbuffers.Builder, stateOffset:flatbuffers.Offset):flatbuffers.Offset {
  StateUpdate.startStateUpdate(builder);
  StateUpdate.addState(builder, stateOffset);
  return StateUpdate.endStateUpdate(builder);
}

unpack(): StateUpdateT {
  return new StateUpdateT(
    this.bb!.createScalarList<number>(this.state.bind(this), this.stateLength())
  );
}


unpackTo(_o: StateUpdateT): void {
  _o.state = this.bb!.createScalarList<number>(this.state.bind(this), this.stateLength());
}
}

export class StateUpdateT implements flatbuffers.IGeneratedObject {
constructor(
  public state: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const state = StateUpdate.createStateVector(builder, this.state);

  return StateUpdate.createStateUpdate(builder,
    state
  );
}
}
