name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.1.6
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: |
            ~/.cargo
            target
          key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
            ${{ github.job }}-${{ runner.os }}-
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: "true"
          default: "true"

      - name: Build
        run: cargo build --locked

      - name: Test
        run: cargo test

  clippy_check:
    name: Clippy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.1.6
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: |
            ~/.cargo
            target
          key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
            ${{ github.job }}-${{ runner.os }}-
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: "true"
          default: "true"

      - name: Use clippy to lint code
        run: cargo clippy -- -D warnings

  fmt_check:
    name: Fmt

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: "true"
          default: "true"

      - name: Check code formatting
        run: cargo fmt -- --check
