name: Sync Issues with Pivotal Tracker

on:
  issues:
    types: [labeled, opened]
    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync Issues
        env:
          PT_API_KEY: ${{ secrets.PT_API_KEY }}
          PT_PROJECT_ID: ${{ secrets.PT_PROJECT_ID }}
          GH_REPOSITORY: ${{ github.repository }}
          GH_ACCESS_TOKEN: ${{ github.token }}
        if: github.event.label.name == 'planned' || github.event.action == 'opened'
        run: python .github/scripts/pt_sync.py
